include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    public_member_api_docs: false

analyzer:
  errors:
    no_default_cases: ignore
    sort_pub_dependencies: ignore
    public_member_api_docs: ignore
    avoid_catches_without_on_clauses: ignore
    flutter_style_todos: ignore
    document_ignores: ignore
    unnecessary_library_directive: ignore
    one_member_abstracts: ignore
    avoid_positional_boolean_parameters: ignore
  exclude:
    - "**/*_generated.dart"
    - "**/*.freezed.dart"
    - "**/*.g.dart"
    - "**/*.gen.dart"
