targets:
  $default:
    builders:
      envied_generator|envied:
        options:
          path: .env
          override: true
      freezed:
        options:
          explicit_to_json: true
      json_serializable:
        options:
          explicit_to_json: true
