export enum ShowmanAction {
  START = "START",
  PAUSE = "PAUSE",
  UNPAUSE = "UNPAUSE",
  NEXT_ROUND = "NEXT_ROUND",
  MANAGE_PLAYERS = "MANAGE_PLAYERS",
  KICK_PLAYER = "KICK_PLAYER",
  CHANGE_SCORE = "CHANGE_SCORE",
  CHANGE_TURN_PLAYER = "CHANGE_TURN_PLAYER",
}
