name: oq_editor
description: "A new Flutter package project."
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  # Local packages
  openapi:
    path: ../../../openapi/dart_sdk/
  siq_file:
    path: ../siq_file/
  oq_compress:
    path: ../oq_compress/
  oq_shared:
    path: ../oq_shared/
  #

  injectable: ^2.5.2
  get_it: ^8.2.0
  watch_it: ^1.7.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  nb_utils: ^7.1.8
  file_picker: ^10.3.3
  crypto: ^3.0.6
  universal_io: ^2.2.2
  universal_web: ^1.1.1
  archive: ^4.0.7
  video_player: ^2.10.0
  video_player_win: ^3.2.0
  fvp: ^0.35.0
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.0.0
  flutter_lints: ^6.0.0
  build_runner: ^2.7.1
  analyzer: ^7.7.1
  freezed: ^3.2.3
  json_serializable: ^6.11.1

dependency_overrides:
  # Fixes linux build
  # Remove after [PR](https://github.com/juliansteenbakker/flutter_secure_storage/pull/923) merged
  # Issue: https://github.com/juliansteenbakker/flutter_secure_storage/issues/920
  flutter_secure_storage_linux:
    git:
      url: https://github.com/m-berto/flutter_secure_storage.git
      path: flutter_secure_storage_linux
      ref: patch-2

flutter:
  uses-material-design: true
