name: oq_editor
description: "A new Flutter package project."
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.11.0
  flutter: ^3.44.0

resolution: workspace

dependencies:
  flutter:
    sdk: flutter

  # Local packages
  openapi: any
  siq_file: any
  oq_compress: any
  oq_shared: any
  #

  auto_route: ^11.1.0
  injectable: ^3.0.0
  get_it: ^9.2.1
  watch_it: ^2.4.2
  freezed_annotation: ^3.1.0
  json_annotation: ^4.12.0
  nb_utils: ^7.3.5
  file_picker: ^11.0.2
  crypto: ^3.0.7
  universal_io: ^2.3.1
  universal_web: ^1.1.1+1
  archive: ^4.0.9
  video_player: ^2.11.1
  video_player_win: ^3.2.2
  path_provider: ^2.1.6
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  auto_route_generator: ^10.5.0
  very_good_analysis: ^10.3.0
  build_runner: ^2.15.0
  analyzer: ^10.2.0
  freezed: ^3.2.5
  json_serializable: ^6.14.0

flutter:
  uses-material-design: true
