name: openapi
version: 1.0.0
description: OpenAPI API client
homepage: homepage

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  dart_mappable: ^4.5.0 # for dart_mappable
  dio: ^5.8.0+1
  freezed_annotation: ^3.1.0 # for freezed
  json_annotation: ^4.9.0
  retrofit: ^4.6.0

dev_dependencies:
  build_runner: ^2.5.4
  freezed: ^3.1.0
  json_serializable: ^6.9.5
  retrofit_generator: ^9.7.0
  dart_mappable_builder: ^4.5.0 # for dart_mappable
  swagger_parser: 1.23.2
