name: Build Server

on:
  workflow_dispatch:
  workflow_call:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-server
  cancel-in-progress: true

jobs:
  pre_job:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      should_run: ${{ steps.found_paths.outputs.server == 'true' || steps.should_force.outputs.should_force == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - id: found_paths
        uses: dorny/paths-filter@v3
        with:
          filters: |
            server:
              - 'server/**'
              - '.github/workflows/build_server.yml'
              - '.github/workflows/test.yml'

      - name: Check if we should force jobs to run
        id: should_force
        run: echo "should_force=${{ github.event_name == 'workflow_dispatch' || github.workflow == 'Release' }}" >> "$GITHUB_OUTPUT"

  test:
    needs: pre_job
    if: ${{ needs.pre_job.outputs.should_run == 'true' }}
    uses: ./.github/workflows/test.yml
    with:
      RUN_CLIENT: false
      RUN_SERVER: true
    permissions:
      contents: read

  build_server:
    needs: test
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' || (!github.event.pull_request.head.repo.fork && github.actor != 'dependabot[bot]') }}
    defaults:
      run:
        working-directory: ./server
    steps:
      - uses: actions/checkout@v4

      - name: Use the latest stable Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ./server/.node-version
          cache: npm
          cache-dependency-path: ./server/package-lock.json

      - run: npm ci
      - run: npm run build
