name: CI

on:
  workflow_dispatch:
  workflow_call:
  pull_request:

jobs:
  test-server:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
      redis:
        image: redis:7
        ports:
          - 6379:6379

    env:
      NODE_ENV: test
      SESSION_SECRET: test_secret
      REDIS_URL: redis://localhost:6379/12
      DB_HOST: localhost
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_DATABASE: test_db

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: cd server && npm ci
      - run: |
          until pg_isready -h localhost -p 5432; do sleep 1; done
      - run: |
          until redis-cli -h localhost -p 6379 ping; do sleep 1; done
      - run: cd server && npm test
